version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3702:3000"
    env_file:
      - .env.prod
    volumes:
      - ./src:/app/src
      - ./views:/app/views